### ISSUE TITLE
Able to add task/event to yesterday or the past days.

### ISSUE THREAD

**Issue by ChaseTiong** [CS2103AUG2016-F11-C1/main#48]
We should not allow user to enter `add task by yesterday` , it should be a invalid command.

I think we should check the parse date by natty is it equal to today or future dates.

**Comment by irvinlim** [comment]
Hmm I think we can just ignore this kind of functionality, I would rather allow the user to be stupid than to try to tell him not to be stupid. He could have reasons for being stupid (lol), and he can enter the task perhaps to remind him that it's overdue (since it appears at the top).

We shouldn't impose that much opinionated behaviour on the user, but instead let him use it as he wants to.

@louietyj Opinion?

**Comment by louietyj** [comment]
Agreed. We can have an alert to notify the user that the deadline is in the past.
