### ISSUE TITLE
Handle invalid parameters

### ISSUE THREAD

**Issue by irvinlim** [CS2103AUG2016-F11-C1/main#50]
Right now, most commands are crashing on invalid parameters, e.g.:
- `update xxx`
- `delete a`
- `delete 1 2`
- `complete test`

How should we handle them? Of course we should show an error in the console, but should we get `process()` to return `false` (so that my view can retain the command in the input box and make it red), or we can just do the same thing, re-render the view, you pass the invalid command string back into `consoleInput`.

**Comment by louietyj** [comment]
Related to #45 

I think this may be part of the disambiguation procedure. If we are coding our controllers to take in something like `update xxx` and call for disambiguation, we will probably be replacing the consoleInput with `update <index> xxx` and show the help for the `update` command somewhere.

It's probably messier, and not a good idea, to write our code in a way that:
- processInput success means view calls controller, controller renders new view and returns true
- processInput fail means view calls controller, controller returns false, view does some logic to render some stuff

Possibly an edge case is where the controller somehow throws an exception, and the view should show a generic "Something bad has happened" error message because the controller couldn't recover from it?

**Comment by irvinlim** [comment]
Don't think the controller should be throwing an unhandled exception, otherwise the controller can't even reach the point to render the new view.

We can do it as per #35, throw the error out of the controller and render it in the console in the new view. Kind of what is currently done in DestroyController and ConfigController.

**Comment by louietyj** [comment]
Yes the controller should never be written to throw an unhandled exception, but if there was something that we didn't think of, we should have a catch-all to show _something_ to the user.

**Comment by louietyj** [comment]
Can we move this to v0.4 so that we can pretend we met all v0.3 milestones? 😂
